### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by abdulsami34** [nimobeeren/scrim-finder#2]
Hey there, 
Can you explain the system a little bit, Can you provide some screenshots.
Is there any tutorial for installing this, I'm a beginner so i need alittle help.

**Comment by nimobeeren** [comment]
Hi,

I'm sorry but I don't really maintain this project anymore. I tried, but I wasn't able to get it working properly. You are free to give it a shot though.

Before you can run the project you need to set up a few things, namely a mongoDB server and a Steam API key. Take a look at issue #1 for some details.

To run the project you have to install the dependencies with `npm install`. Then go into the `client` directory and again run `npm install`. Then go back to the root directory and run `npm start`. That should start both the server and the client and open the main page in your browser.

Here are some screenshots of the final product:

![Home small](https://user-images.githubusercontent.com/12124298/54850878-a112d380-4ce8-11e9-949f-ded59d9cfc53.png)

![Create Post Form](https://user-images.githubusercontent.com/12124298/54850901-b2f47680-4ce8-11e9-80aa-12f42ecf85c6.png)

![Create Post Form](https://user-images.githubusercontent.com/12124298/54850909-b7209400-4ce8-11e9-88fd-e3b664be9e33.png)
