### ISSUE TITLE
Error installing scrim-finder

### ISSUE THREAD

**Issue by ShorMario** [nimobeeren/scrim-finder#6]
Hello!
I am interested in this project and I intend to use it in my community, but I have an error with the installation.

 **ERROR1**
![image](https://user-images.githubusercontent.com/36205967/84595881-4d8f2700-ae52-11ea-970a-4d5cb5571220.png)

When I go run _**yarn install**_  on **/client** the error above( **ERROR1**) apearce and when start the server with the command **_yarn start_**. on root I have this **ERROR2**

**ERROR2**
![image](https://user-images.githubusercontent.com/36205967/84598058-dc567080-ae5f-11ea-985a-7503e99eebcd.png)

Can you help me?
Thanks!

**Comment by nimobeeren** [comment]
Hi @ShorMario! Looking at the error, it seems like you need to install [Python 2](https://www.python.org/downloads/release/python-2718/) on your machine.

**Comment by ShorMario** [comment]
Hello! @nimobeeren 

The problem persisted but i search on "**package**"   and when I change this line  **"node-sass-chokidar": "^1.4.0",**  to **"node-sass-chokidar": "^1.5.0",** the project work!!


Now I have a question I read de #3  I don't understand how I why put the login to work.

**Comment by nimobeeren** [comment]
@ShorMario the first thing I'd point you to is the Usage seciton of the README. You'll have to be more specific in your question if you want more specific help.

**Comment by ShorMario** [comment]
@nimobeeren I can't login basically, I edit the localhost but don't work

**Comment by nimobeeren** [comment]
@ShorMario I'm not actively maintaining this project (and don't plan to do so in the future), so I can't guarantee that everything will work as expected. That said, as long as the config is filled in correctly, it should work. Are you sure everything is filled in correctly? The important bits are `host`, `mongoServer` and `steamApiKey`. You need all of those in order to log in.
